version: "3.9"

services:
  poshart-loadbalancer:
    image: poshart/poshart-haproxy
    ports:
      - 443:443
      - 1936:1936
    links:
      - poshart-app1
      - poshart-app2
    restart: always
    expose:
      - 443

  poshart-app1:
    image: poshart/poshart-app
    volumes:
      - ./poshart-compose/app:/app
    ports:
      - 8081:8080
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_URL: jdbc:mysql://poshart-db-proxy:6033/poshart
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: GEIposhart#333
      POSHART_INTERNAL_URI: http://poshart-loadbalancer-internal:8080
    links:
      - poshart-db
      - poshart-loadbalancer-internal
    restart: on-failure
    expose:
      - 8080
    command: [ "./wait-for-it.sh", "poshart-db:3306", "--", "java", "-jar", "Poshart-0.0.1-SNAPSHOT.jar" ]

  poshart-app2:
    image: poshart/poshart-app
    volumes:
      - ./poshart-compose/app:/app
    ports:
      - 8082:8080
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_DATASOURCE_URL: jdbc:mysql://poshart-db-proxy:6033/poshart
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: GEIposhart#333
      POSHART_INTERNAL_URI: http://poshart-loadbalancer-internal:8080
    links:
      - poshart-db
      - poshart-loadbalancer-internal
    restart: on-failure
    expose:
      - 8080
    command: [ "./wait-for-it.sh", "poshart-db:3306", "--", "java", "-jar", "Poshart-0.0.1-SNAPSHOT.jar" ]

  poshart-loadbalancer-internal:
    image: poshart/poshart-haproxy-internal
    ports:
      - 1937:1937
    links:
      - poshart-internal-app1
      - poshart-internal-app2
    restart: always
    expose:
      - 8080

  poshart-internal-app1:
    image: poshart/poshart-internal-app
    volumes:
      - ./poshart-compose/internal-app1:/internal-app
    restart: on-failure
    expose:
      - 8080
      
  poshart-internal-app2:
    image: poshart/poshart-internal-app
    volumes:
      - ./poshart-compose/internal-app2:/internal-app
    restart: on-failure
    expose:
      - 8080
      
  poshart-db-proxy:
    image: proxysql/proxysql:2.3.2
    ports:
      - 6032:6032
      - 6033:6033
    volumes:
      - ./poshart-compose/proxysql/proxysql.cnf:/etc/proxysql.cnf
      - ./poshart-compose/proxysql/data:/var/lib/proxysql
    links:
      - poshart-db-master
      - poshart-db-slave
    expose:
      - 6032

  poshart-db-master:
    image: poshart/poshart-sql-master
    ports:
      -  3306:3306
    volumes:
      - ./poshart-compose/sql/master/data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: GEIposhart#333
      MYSQL_DATABASE: poshart
    restart: on-failure
    expose:
      - 3306
      
  poshart-db-slave:
    image: poshart/poshart-sql-slave
    ports:
      -  3307:3306
    volumes:
      - ./poshart-compose/sql/slave/data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: GEIposhart#333
      MYSQL_DATABASE: poshart
    links:
      - poshart-db-master
    restart: on-failure
    expose:
      - 3306
volumes:
  poshart-compose:
