version: "3.9"

services:
  poshart-app:
    image: poshart/poshart-app
    ports:
      - 443:443
    volumes:
      - ./poshart-compose/app:/app
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_URL: jdbc:mysql://poshart-db/poshart
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: GEIposhart#333
      POSHART_INTERNAL_URI: http://poshart-internal-app:8080
    links:
      - mysql
      - poshart-internal-app
    command: [ "./wait-for-it.sh", "poshart-db:3306", "--", "java", "-jar", "Poshart-0.0.1-SNAPSHOT.jar" ]

  poshart-internal-app:
    image: poshart/poshart-internal-app
    volumes:
      - ./poshart-compose/internal-app:/internal-app

  poshart-db:
    image: mysql:5.7
    volumes:
      - ./poshart-compose/sql:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: GEIposhart#333
      MYSQL_DATABASE: poshart